#!/bin/sh
### BEGIN INIT INFO
# Provides:          aesdsocket
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
### END INIT INFO

DAEMON=/usr/bin/aesdsocket
PIDFILE=/var/run/aesdsocket.pid
LOGFILE=/var/log/aesdsocket.log

case "$1" in
  start)
    echo "Starting aesdsocket..."
    start-stop-daemon --start --quiet \
      --make-pidfile --pidfile "$PIDFILE" \
      --exec "$DAEMON" -- -d >> "$LOGFILE" 2>&1
    ;;
  stop)
    echo "Stopping aesdsocket..."
    start-stop-daemon --stop --quiet \
      --pidfile "$PIDFILE" --signal TERM
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
    ;;
esac
exit 0
